ipa320 default gitignore
ipa320/care-o-bot pull request #35
Opened 2017-02-08 09:13 UTC by ipa-fxm

@ipa-mig @ipa-fmw @ipa-nhg @ipa-bnm 
How do you like this one?
related to https://github.com/ipa320/cob_calibration_data/pull/118

I'm not sure about `bin` and `lib` as we sometimes have files in these folder which we don't want to be gitignored...e.g. cob_extern....
I think we could remove `build`, `bin` and `lib` as `catkin` does not create those folders in the source space anymore...

2017-02-08 12:15 UTC, mgruhler requested changes
I would add:

```
# VI/VIM
*.swp
```

Also, one could think about libraries and compiled objects (`*.slo, *.lo, *.o, *.so, *.dylib, *.lai, *.la, *.a`) but I don't think we need those.

2017-02-08 12:15 UTC, ipa-mig commented on .gitignore
> +CATKIN_IGNORE
yay, I especially like this one!

2017-02-08 12:15 UTC, ipa-mig commented on .gitignore
> +lib/
I would remove `build`, as this is definitely not required. However, I'd keep `bin` and `lib`. This does not hurt and actually forces us to think about if what we are doing makes sense.

As soon as you have added something in those folders (with `git add -f`),  those files are tracked regularly.

2017-02-09 13:56 UTC, benmaidel approved these changes

2017-02-09 16:16 UTC, ipa-fxm commented
considered @ipa-mig's comments
@ipa-fmw please provide feedback...

After approval, I will provide PRs to the relevant repositories

2017-02-09 16:21 UTC, mgruhler approved these changes

2017-02-09 16:36 UTC, ipa-fxm commented
Here is a list of candidates for the default .gitignore:

### bringup packages
 - cob_calibration_data
 - cob_command_tools
 - cob_common
 - cob_control
 - cob_docking
 - cob_driver
 - cob_environments
 - cob_extern
 - cob_gazebo_plugins
 - cob_hand
 - cob_manipulation
 - cob_navigation
 - cob_perception_common
 - cob_robots
 - cob_simulation
 - cob_substitute
 - schunk_modular_robotics
 - schunk_robots
 - sick_flexisoft

### msh packages
 - cob_people_perception
 - ipa_navigation
 - ipa_navigation_common
 - ipa_navigation_driver
 - ipa_navigation_localization
 - ipa_navigation_perception
 - ipa_navigation_planning
 - ipa_navigation_sandbox
 - msh
 - msh_common
 - msh_gui
 - msh_voice_control


Did I forget something? Should any of the packages above **NOT** use the default .gitignore?

2017-02-10 16:13 UTC, ipa-mig commented
all navigation packages could use the new one. 

I guess the rest should be fine as well. I'm not sure about msh, though.

2017-02-10 16:13 UTC, ipa-mig commented
Still waiting for @ipa-fmw's feedback, though?

2017-02-10 18:18 UTC, ipa-fxm commented
Yes, I'd like to see approval of @ipa-fmw and @ipa-nhg for this before creating 30 PRs...

2017-02-12 21:28 UTC, floweisshardt approved these changes
looks good to me. OK to roll out to all repos.

2017-02-15 14:33 UTC, ipa-fxm commented
Well, I'll go on with this now...I have three approvals...

2017-02-15 14:34 UTC, merged

2017-02-15 14:54 UTC, ipa-fxm commented
updated all repos from the list above!