add robot tools to care-o-bot-robot variant
ipa320/care-o-bot pull request #38
Opened 2017-02-20 16:31 UTC by ipa-fmw

2017-02-21 06:22 UTC, fmessmer submitted a review, later dismissed

2017-02-21 06:22 UTC, ipa-fxm commented on care_o_bot_robot/package.xml
> +  <exec_depend>vim</exec_depend>
I don't like this approach too much...
Can we add a new meta-package e.g. `care_o_bot_tools` within this repo which defines the `exec_depend` to those system tools? And then we have `care_o_bot_robots` depend on `car_o_bot_tools`...

2017-02-22 07:16 UTC, ipa-fmw commented on care_o_bot_robot/package.xml
> +  <exec_depend>vim</exec_depend>
What would be the difference?

2017-05-22 13:43 UTC, ipa-fmw commented
make sure to add everything from setup_cob4 `InstallCob4.sh` script:

```
sudo apt-get install vim tree gitg git-gui meld curl openjdk-6-jdk zsh terminator language-pack-de language-pack-en ipython nmap -y --force-yes
sudo apt-get install --install-recommends linux-generic-lts-wily -y --force-yes
sudo apt-get install openssh-server -y --force-yes
sudo apt-get install ros-indigo-rosbash -y --force-yes
sudo apt-get install ntp -y --force-yes
sudo apt-get install apt-cacher-ng
sudo apt-get install nfs-kernel-server autofs -y --force-yes
sudo apt-get install zlib1g-dev uuid-dev libmnl-dev gcc make git autoconf autoconf-archive autogen automake pkg-config curl -y --force-yes
```

2017-07-03 19:16 UTC, fmessmer requested changes
Structure approved....please add missing tools from https://github.com/ipa320/care-o-bot/pull/38#issuecomment-303103713

2017-07-03 19:16 UTC, ipa-fxm commented on care_o_bot_robot/package.xml
> +  <exec_depend>vim</exec_depend>
Ok then, I approve to add them here...
still please consider https://github.com/ipa320/care-o-bot/pull/38#issuecomment-303103713

2017-07-07 16:36 UTC, ipa-fxm commented
I tested this with the fresh system for kinetic...
But `rosdep install --from-paths src -i -y` does not install packages like `htop`, 'blender', ....
It installs all other dependencies listed in `src`...but not those...don't know why and also do not no how to debug....

2017-07-13 14:48 UTC, ipa-fxm commented
@ipa-fmw according to @ipa-mdl `exec_depend` entries are not considered by `rosdep install` for `meta-packages`...

2017-07-13 16:12 UTC, ipa-mdl commented
> according to @ipa-mdl exec_depend entries are not considered by rosdep install for meta-packages...

I meant that somehow meta-packages don't get processed at all..

2017-09-29 19:26 UTC, ipa-fxm commented
fixed in#48

2017-09-29 19:26 UTC, closed without merging