Travis extensions
ipa320/care-o-bot pull request #47
Opened 2017-07-28 07:03 UTC by ipa-fxm

implements parts of #45 
if we agree on this to be the new default...these updates should be applied to the other repos, too (see list in #45)

@ipa-jba @ipa-fez @ipa-rmb

2017-07-28 07:15 UTC, ipa-fez requested changes

2017-07-28 07:15 UTC, ipa-fez commented on README.md
>  ics)
Maybe fix this extra linebreak aswell.

2017-07-28 11:44 UTC, floweisshardt approved these changes

2017-07-28 13:33 UTC, ipa-rmb approved these changes

2017-07-31 06:59 UTC, ipa-fez approved these changes

2017-07-31 07:13 UTC, ipa-fxm commented
ok, then I'll prepare PRs for the other repos...

2017-07-31 12:57 UTC, jabbenseth approved these changes

2017-08-01 12:06 UTC, merged